from pathlib import Path
import json
import sqlite3

ROOT = Path(__file__).resolve().parents[1]
JSON_DIR = ROOT / "JSON_Edit"
SQL_DIR = ROOT / "SQL"
DB_PATH = SQL_DIR / "IFCAllData.db"
SQL_FILE = SQL_DIR / "IFCAllData.sql"
FIELD_MAP_FILE = SQL_DIR / "IFCAllData.field_map.json"


def quote_ident(name: str) -> str:
	"""Safely quote SQLite identifiers (column/table names)."""
	return '"' + name.replace('"', '""') + '"'


def load_field_map(field_map_path: Path) -> dict[str, list[tuple[str, str]]]:
	"""Load logical field map generated by Generate-IFCAllData-FieldMap.py."""
	if not field_map_path.exists():
		raise FileNotFoundError(
			f"Field map file not found: {field_map_path}. Run PyToSQL/Generate-IFCAllData-FieldMap.py first."
		)

	payload = json.loads(field_map_path.read_text(encoding="utf-8"))
	logical = payload.get("logical_field_map")
	if not isinstance(logical, dict) or not logical:
		raise ValueError(f"Invalid logical_field_map in {field_map_path}")

	field_map: dict[str, list[tuple[str, str]]] = {}
	for field_name in sorted(logical.keys()):
		candidates = logical[field_name]
		field_map[field_name] = [tuple(candidate) for candidate in candidates]

	return field_map


def get_first_value(prop_lookup: dict, candidates: list[tuple[str, str]]):
	"""Priority-based value selection, same style as model loader."""
	for category, display_name in candidates:
		value = prop_lookup.get((category, display_name), None)
		if value is not None and str(value).strip() != "":
			return value
	return None


def normalize_sql_value(value):
	"""Convert nested JSON values to text for SQLite storage."""
	if isinstance(value, (dict, list)):
		return json.dumps(value, ensure_ascii=False)
	return value


def build_rows(items: list[dict], source_file: str, field_map: dict[str, list[tuple[str, str]]]) -> list[tuple]:
	rows = []
	ordered_columns = list(field_map.keys())

	for item_index, item in enumerate(items, start=1):
		prop_lookup = {}
		for prop in item.get("Properties", []):
			category = str(prop.get("category", "")).strip()
			display_name = str(prop.get("displayName", "")).strip()
			if category and display_name:
				# Keep first non-empty value for the same (category, displayName).
				key = (category, display_name)
				incoming = prop.get("value", None)
				if key not in prop_lookup or (prop_lookup[key] is None and incoming is not None):
					prop_lookup[key] = incoming

		row = [source_file, item_index]
		for column_name in ordered_columns:
			raw_value = get_first_value(prop_lookup, field_map[column_name])
			row.append(normalize_sql_value(raw_value))
		rows.append(tuple(row))

	return rows


def main() -> None:
	json_paths = sorted(JSON_DIR.glob("*.json"))
	if not json_paths:
		raise FileNotFoundError(f"No JSON files found in {JSON_DIR}")

	field_map = load_field_map(FIELD_MAP_FILE)

	# Avoid collisions with base table columns.
	reserved_columns = {"ID", "SOURCE_FILE", "ITEM_INDEX"}
	db_field_map: dict[str, list[tuple[str, str]]] = {}
	for logical_name in field_map:
		db_name = logical_name
		if db_name in reserved_columns:
			db_name = f"FIELD_{db_name}"

		suffix = 2
		while db_name in db_field_map:
			db_name = f"{logical_name}_{suffix}"
			suffix += 1

		db_field_map[db_name] = field_map[logical_name]

	conn = sqlite3.connect(DB_PATH)
	cur = conn.cursor()

	table_name = "IFCAllData"
	base_columns = [
		"ID INTEGER PRIMARY KEY AUTOINCREMENT",
		"SOURCE_FILE TEXT",
		"ITEM_INDEX INTEGER",
	]
	field_columns = [f"{quote_ident(column)} TEXT" for column in db_field_map.keys()]

	# Rebuild cleanly with the new flattened schema.
	cur.execute(f"DROP TABLE IF EXISTS {quote_ident(table_name)}")
	create_sql = (
		f"CREATE TABLE {quote_ident(table_name)} ("
		+ ", ".join(base_columns + field_columns)
		+ ")"
	)
	cur.execute(create_sql)
	conn.commit()

	insert_columns = ["SOURCE_FILE", "ITEM_INDEX"] + list(db_field_map.keys())
	insert_columns_sql = ", ".join(quote_ident(column) for column in insert_columns)
	placeholders = ", ".join("?" for _ in insert_columns)
	insert_sql = f"INSERT INTO {quote_ident(table_name)} ({insert_columns_sql}) VALUES ({placeholders})"

	print(f"JSON files detected: {len(json_paths)}")
	print(f"Logical fields loaded from map: {len(field_map)}")
	print(f"DB columns after collision-safe mapping: {len(db_field_map)}")
	print(f"Using field map file: {FIELD_MAP_FILE}")

	total_inserted = 0
	for path in json_paths:
		with open(path, "r", encoding="utf-8") as f:
			items = json.load(f)

		rows = build_rows(items, path.name, db_field_map)
		cur.executemany(insert_sql, rows)
		conn.commit()

		total_inserted += len(rows)
		print(f"Inserted {len(rows):,} rows from {path.name}")

	print(f"Total rows inserted: {total_inserted:,}")

	# Run SQL file as requested.
	if SQL_FILE.exists():
		sql_text = SQL_FILE.read_text(encoding="utf-8")
		if sql_text.strip():
			cur.executescript(sql_text)
			conn.commit()
			print(f"Ran SQL file: {SQL_FILE.name}")
		else:
			print(f"SQL file is empty: {SQL_FILE.name}")
	else:
		print(f"SQL file not found: {SQL_FILE}")

	# Verification checks.
	cur.execute(f"SELECT COUNT(*) FROM {quote_ident(table_name)}")
	row_count = cur.fetchone()[0]
	print(f"Verification row count in {table_name}: {row_count:,}")

	# Show sample columns for sanity check.
	sample_field_cols = list(db_field_map.keys())[:2]
	sample_columns = ["ID", "SOURCE_FILE", "ITEM_INDEX"] + sample_field_cols
	sample_sql = (
		f"SELECT {', '.join(quote_ident(column) for column in sample_columns)} "
		f"FROM {quote_ident(table_name)} LIMIT 3"
	)
	cur.execute(sample_sql)
	sample_rows = cur.fetchall()
	print("Sample rows:")
	for row in sample_rows:
		print(row)

	conn.close()


if __name__ == "__main__":
	main()
