DROP TABLE IF EXISTS "ASTIDC-AssetData";

CREATE TABLE "ASTIDC-AssetData" AS
SELECT
	ID,
	SOURCE_FILE,
	ITEM_INDEX,
	NAME,
	GLOBALID,
	GUID,
	COBIE AS "COBie",
	ABB_CLASSIFICATION_Y,
	ABB_NOTE,
	ABB_POSITION_NO,
	ABB_SUPPLIER,
	ABB_UNIT,
	DB_PART_DESC,
	DB_PART_NO,
	DB_PART_REV,
	DB_PART_TYPE,
	DISCIPLINE
FROM IFCAllData
WHERE SOURCE_FILE IN (
	'ASTIDC-STAN-HE-EPD-MVB1-M-E-0002.json',
	'ASTIDC-STAN-HE-MPD-RHP1-M-M-0001.json',
	'ASTIDC-STAN-HE-MPD-TXBP1-M-M-0001.json'
)
AND GUID IS NOT NULL
AND TRIM(CAST(GUID AS TEXT)) <> '';

SELECT
	*
FROM "ASTIDC-AssetData"
ORDER BY SOURCE_FILE, ITEM_INDEX
LIMIT 100;