CREATE TABLE IF NOT EXISTS IFCModelData (
	ID               INTEGER PRIMARY KEY AUTOINCREMENT,
	SOURCE_FILE      TEXT,
	NAME             TEXT,
	TYPE             TEXT,
	UNIT             TEXT,
	GUID             TEXT,
	GLOBAL_ID        TEXT,
	OBJECT_TYPE      TEXT,
	MATERIAL         TEXT,
	NX_AREA          TEXT,
	NX_VOLUME        TEXT,
	NX_VOLUME_SOURCE TEXT,
	NX_WEIGHT        TEXT,
	NX_WEIGHT_SOURCE TEXT
);

SELECT
	ID,
	SOURCE_FILE,
	NAME,
	TYPE,
	UNIT,
	GUID,
	GLOBAL_ID,
	OBJECT_TYPE,
	MATERIAL,
	NX_AREA,
	NX_VOLUME,
	NX_VOLUME_SOURCE,
	NX_WEIGHT,
	NX_WEIGHT_SOURCE
FROM IFCModelData
ORDER BY ID
LIMIT 100;